# -*- coding: utf-8 -*-
"""Curve fitting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14hSyrnvcowBTNWSgOjIZncWRVBOfvLDi
"""

import numpy as np
import pandas as pd
from scipy.optimize import differential_evolution, least_squares
import matplotlib.pyplot as plt
from google.colab import files

"""Loading data

"""

uploaded = files.upload()
df = pd.read_csv(list(uploaded.keys())[0])
x_data = df['x'].values
y_data = df['y'].values
n = len(x_data)

print(f"Loaded {n} points")
print(f"X range: [{x_data.min():.1f}, {x_data.max():.1f}]")
print(f"Y range: [{y_data.min():.1f}, {y_data.max():.1f}]")

"""Defining parametric equations"""

def curve(t, theta, M, X):
    e = np.exp(M * np.abs(t))
    s = np.sin(0.3 * t)
    x = t * np.cos(theta) - e * s * np.sin(theta) + X
    y = 42 + t * np.sin(theta) + e * s * np.cos(theta)
    return x, y

"""Optimization"""

def error_func(p):
    theta, M, X, a, b = p
    t = a * np.arange(n) + b
    if np.any(t < 6) or np.any(t > 60):
        return 1e10
    x_pred, y_pred = curve(t, theta, M, X)
    return np.sum(np.abs(x_pred - x_data) + np.abs(y_pred - y_data))

"""Setting parameter bounds"""

bounds = [
    (0, np.radians(50)),
    (-0.05, 0.05),
    (0, 100),
    (0.01, 2.0),
    (5.0, 10.0)
]

"""First pass : Global search"""

res1 = differential_evolution(error_func, bounds, maxiter=800, seed=42, workers=-1)
print(f"Initial solution found (error={res1.fun:.2f})")

"""Second pass"""

def err_vec(p):
    theta, M, X, a, b = p
    t = a * np.arange(n) + b
    if np.any(t < 6) or np.any(t > 60):
        return np.ones(2 * n) * 1e6
    x_pred, y_pred = curve(t, theta, M, X)
    return np.concatenate([x_pred - x_data, y_pred - y_data])

res2 = least_squares(
    err_vec, res1.x,
    bounds=([0, -0.05, 0, 0.01, 5.0], [np.radians(50), 0.05, 100, 2.0, 10.0]),
    max_nfev=50000
)

"""Extracting and displaying results"""

theta, M, X, a, b = res2.x
t_opt = a * np.arange(n) + b
x_fit, y_fit = curve(t_opt, theta, M, X)

total_err = np.sum(np.abs(x_fit - x_data) + np.abs(y_fit - y_data))
avg_err = total_err / n

print("\n--- RESULTS ---")
print(f"theta = {theta:.8f} rad = {np.degrees(theta):.6f}°")
print(f"M = {M:.8f}")
print(f"X = {X:.8f}")
print(f"a = {a:.6f}")
print(f"b = {b:.6f}")
print(f"t range: {t_opt.min():.2f} → {t_opt.max():.2f}")
print(f"Total error: {total_err:.4f}")
print(f"Average error: {avg_err:.4f}")

"""Plot 1 - Fitted curve vs acutal data
Plot 2 - Errors over t
"""

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
idx = np.argsort(t_opt)

ax1.scatter(x_data, y_data, s=20, c='blue', alpha=0.6, label='Actual')
ax1.plot(x_fit[idx], y_fit[idx], 'r-', lw=2, label='Fitted')
ax1.legend()
ax1.set_title('Data vs Fitted Curve')
ax1.axis('equal')
ax1.grid(True, alpha=0.3)

ax2.plot(t_opt[idx], np.abs(x_data[idx] - x_fit[idx]), 'b-', lw=1.5, label='X error')
ax2.plot(t_opt[idx], np.abs(y_data[idx] - y_fit[idx]), 'r-', lw=1.5, label='Y error')
ax2.legend()
ax2.set_title('Error over t')
ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

"""Preparing DESMOS equation"""

print("\n--- DESMOS EQUATION ---")
desmos = f"\\left(t\\cos({theta})-e^{{{M}\\left|t\\right|}}\\sin(0.3t)\\sin({theta})+{X},42+t\\sin({theta})+e^{{{M}\\left|t\\right|}}\\sin(0.3t)\\cos({theta})\\right)"
print(desmos)